name: Lint pull request name

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
     branches:
      - main

jobs:
  lint-pr-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          cache: npm

    - name: Install Dependencies
      run: npm install @commitlint/config-conventional
    - name: Pull request linter action
      uses: JulienKode/pull-request-name-linter-action@v0.5.0

