name: Lint pull request name

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main

jobs:
  pr-name-linter:
    name: Lint pull request name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          cache: npm
      
      - name: Install dependencies
        run: npm install @commitlint/config-conventional
      
      - name: Lint pull request name
        uses: JulienKode/pull-request-name-linter-action@v0.5.0

